**Hyperparameter Tuning HandsOn**

In [1]:
import numpy as np
import pandas as pd
from scipy.stats import loguniform

from sklearn.model_selection import(
    train_test_split,
    GridSearchCV,
    RandomizedSearchCV
)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

**Load Data and Clean**

In [2]:
df = pd.read_csv("diabetes.csv")

In [4]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [6]:
X = df.drop(columns= ["Outcome"])
y = df["Outcome"]

**Train Test Split**

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [8]:
print("Full Dataset Size:",X.shape)
print("Training data size:",X_train.shape)
print("Test data size:",X_test.shape)

Full Dataset Size: (768, 8)
Training data size: (614, 8)
Test data size: (154, 8)

**1. Pipeline - (Scaler + Model)**

In [10]:
pipeline = Pipeline(
    [
        ("scalar",StandardScaler()),
        ("model",SVC())
    ]
)

**2. Grid Search CV(Tries all Possible Combinations)**

In [12]:
param_grid = [
    {
        "model__kernel" : ["linear"],
        "model__C" : [0.1, 1, 10, 100]
    },
    {
        "model__kernel" : ["rbf"],
        "model__C" : [0.1, 1, 10, 100],
        "model__gamma" : ["scale", "auto", 0.01, 0.1]
    },
    {
        "model__kernel" : ["poly"],
        "model__C" : [0.1, 1, 10],
        "model__gamma" : ["scale", "auto", 0.01, 0.1],
        "model__degree" : [2, 3, 4]
    }
]

In [15]:
grid = GridSearchCV(
    estimator= pipeline,
    param_grid= param_grid,
    cv = 5,
    scoring="accuracy",
    return_train_score=True,
    n_jobs= -1
)

In [16]:
grid.fit(X_train,y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scalar', StandardScaler()),
                                       ('model', SVC())]),
             n_jobs=-1,
             param_grid=[{'model__C': [0.1, 1, 10, 100],
                          'model__kernel': ['linear']},
                         {'model__C': [0.1, 1, 10, 100],
                          'model__gamma': ['scale', 'auto', 0.01, 0.1],
                          'model__kernel': ['rbf']},
                         {'model__C': [0.1, 1, 10], 'model__degree': [2, 3, 4],
                          'model__gamma': ['scale', 'auto', 0.01, 0.1],
                          'model__kernel': ['poly']}],
             return_train_score=True, scoring='accuracy')

In [17]:
print("GRID SEARCH CV - Results")
print("Best Params: ",grid.best_params_)
print("Best CV Accuracy: ",grid.best_score_)

GRID SEARCH CV - Results
Best Params:  {'model__C': 10, 'model__gamma': 0.01, 'model__kernel': 'rbf'}
Best CV Accuracy:  0.7785419165667067

In [19]:
#Evaluation on global test set(Unseen Data)
test_accuracy = grid.score(X_test, y_test)*100
print(f"Test Accuracy:{test_accuracy:.3f}")

Test Accuracy:75.325

**3. Analyzing Results**

In [20]:
grid.cv_results_

{'mean_fit_time': array([0.05064659, 0.04764218, 0.10332017, 0.58270869, 0.02645841,
        0.03007274, 0.02946386, 0.03775339, 0.04051323, 0.02810893,
        0.02715712, 0.02540207, 0.03184576, 0.03863492, 0.02516298,
        0.03337903, 0.06752925, 0.06732478, 0.03757653, 0.06944585,
        0.02597132, 0.02764654, 0.03088026, 0.02791905, 0.02722802,
        0.03100324, 0.02889037, 0.02482915, 0.03268304, 0.03104029,
        0.02549629, 0.04319611, 0.0376091 , 0.0337183 , 0.0269949 ,
        0.02924781, 0.02907057, 0.03004184, 0.04040928, 0.03518357,
        0.03645906, 0.03208179, 0.02854428, 0.03703008, 0.05486426,
        0.05694613, 0.02678456, 0.04424644, 0.05896935, 0.05705051,
        0.0245667 , 0.04080853, 0.05494418, 0.05031509, 0.02550821,
        0.04061251]),
 'std_fit_time': array([0.00956763, 0.01225033, 0.01021181, 0.16342916, 0.00455619,
        0.00750349, 0.00557097, 0.01317014, 0.00872441, 0.00392211,
        0.00300422, 0.00200679, 0.00223843, 0.00373364, 0.00175343,
        0.00275708, 0.00569634, 0.00586696, 0.0018166 , 0.00344439,
        0.00409366, 0.00413797, 0.00537986, 0.00365308, 0.00275992,
        0.00429085, 0.00381876, 0.00183851, 0.00563491, 0.00319553,
        0.00407951, 0.00889264, 0.00488282, 0.00811541, 0.00238679,
        0.00385467, 0.00432379, 0.00424502, 0.00957194, 0.01128907,
        0.00542747, 0.00233281, 0.00614505, 0.00348352, 0.01080038,
        0.01397872, 0.00403616, 0.00464435, 0.01072263, 0.00830918,
        0.002688  , 0.00115492, 0.008828  , 0.0093634 , 0.00453776,
        0.00284784]),
 'mean_score_time': array([0.01351342, 0.00893421, 0.00621309, 0.00628457, 0.01839957,
        0.02351375, 0.02041984, 0.0231113 , 0.02242203, 0.0224452 ,
        0.01822891, 0.01772642, 0.01476188, 0.01589756, 0.01553941,
        0.01616569, 0.01571207, 0.01502643, 0.01535044, 0.01500425,
        0.01131005, 0.01043143, 0.01072111, 0.00993385, 0.00888724,
        0.01562195, 0.00898066, 0.009132  , 0.00962052, 0.0098969 ,
        0.01729131, 0.0128469 , 0.00970941, 0.00899439, 0.01544032,
        0.00756326, 0.00889082, 0.0089756 , 0.01200619, 0.00934176,
        0.00905128, 0.00884719, 0.01031971, 0.00802531, 0.0070231 ,
        0.01409931, 0.01126823, 0.01362   , 0.00894761, 0.00794244,
        0.00885558, 0.00857763, 0.00859656, 0.00758777, 0.0089334 ,
        0.00931253]),
 'std_score_time': array([0.00583083, 0.0013151 , 0.00038188, 0.00069593, 0.00220114,
        0.00390379, 0.00313215, 0.01159924, 0.01035627, 0.00556159,
        0.00421316, 0.0024617 , 0.00091119, 0.00065124, 0.0005533 ,
        0.00378533, 0.00196945, 0.00109395, 0.00243069, 0.00125315,
        0.00459271, 0.0039016 , 0.00312313, 0.00193735, 0.00117578,
        0.00609731, 0.00099695, 0.00203496, 0.00071352, 0.0022084 ,
        0.01178943, 0.00391944, 0.00181101, 0.00049371, 0.01011404,
        0.00053977, 0.00127008, 0.0011211 , 0.00175637, 0.0024    ,
        0.00217318, 0.0007638 , 0.0040261 , 0.00109483, 0.00100676,
        0.01280423, 0.0035695 , 0.00846668, 0.00133187, 0.0017999 ,
        0.00171586, 0.00183328, 0.00080515, 0.00084044, 0.00165295,
        0.00222337]),
 'param_model__C': masked_array(data=[0.1, 1.0, 10.0, 100.0, 0.1, 0.1, 0.1, 0.1, 1.0, 1.0,
                    1.0, 1.0, 10.0, 10.0, 10.0, 10.0, 100.0, 100.0, 100.0,
                    100.0, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1,
                    0.1, 0.1, 0.1, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
                    1.0, 1.0, 1.0, 1.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0,
                    10.0, 10.0, 10.0, 10.0, 10.0, 10.0],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=1e+20),
 'param_model__kernel': masked_array(data=['linear', 'linear', 'linear', 'linear', 'rbf', 'rbf',
                    'rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'rbf',
                    'rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'rbf', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly',
                    'poly', 'poly', 'poly', 'poly', 'poly', 'poly', 'poly'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_model__gamma': masked_array(data=[--, --, --, --, 'scale', 'auto', 0.01, 0.1, 'scale',
                    'auto', 0.01, 0.1, 'scale', 'auto', 0.01, 0.1, 'scale',
                    'auto', 0.01, 0.1, 'scale', 'auto', 0.01, 0.1, 'scale',
                    'auto', 0.01, 0.1, 'scale', 'auto', 0.01, 0.1, 'scale',
                    'auto', 0.01, 0.1, 'scale', 'auto', 0.01, 0.1, 'scale',
                    'auto', 0.01, 0.1, 'scale', 'auto', 0.01, 0.1, 'scale',
                    'auto', 0.01, 0.1, 'scale', 'auto', 0.01, 0.1],
              mask=[ True,  True,  True,  True, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_model__degree': masked_array(data=[--, --, --, --, --, --, --, --, --, --, --, --, --, --,
                    --, --, --, --, --, --, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4,
                    4, 4, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 2, 2, 2, 2,
                    3, 3, 3, 3, 4, 4, 4, 4],
              mask=[ True,  True,  True,  True,  True,  True,  True,  True,
                     True,  True,  True,  True,  True,  True,  True,  True,
                     True,  True,  True,  True, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False],
        fill_value=999999),
 'params': [{'model__C': 0.1, 'model__kernel': 'linear'},
  {'model__C': 1, 'model__kernel': 'linear'},
  {'model__C': 10, 'model__kernel': 'linear'},
  {'model__C': 100, 'model__kernel': 'linear'},
  {'model__C': 0.1, 'model__gamma': 'scale', 'model__kernel': 'rbf'},
  {'model__C': 0.1, 'model__gamma': 'auto', 'model__kernel': 'rbf'},
  {'model__C': 0.1, 'model__gamma': 0.01, 'model__kernel': 'rbf'},
  {'model__C': 0.1, 'model__gamma': 0.1, 'model__kernel': 'rbf'},
  {'model__C': 1, 'model__gamma': 'scale', 'model__kernel': 'rbf'},
  {'model__C': 1, 'model__gamma': 'auto', 'model__kernel': 'rbf'},
  {'model__C': 1, 'model__gamma': 0.01, 'model__kernel': 'rbf'},
  {'model__C': 1, 'model__gamma': 0.1, 'model__kernel': 'rbf'},
  {'model__C': 10, 'model__gamma': 'scale', 'model__kernel': 'rbf'},
  {'model__C': 10, 'model__gamma': 'auto', 'model__kernel': 'rbf'},
  {'model__C': 10, 'model__gamma': 0.01, 'model__kernel': 'rbf'},
  {'model__C': 10, 'model__gamma': 0.1, 'model__kernel': 'rbf'},
  {'model__C': 100, 'model__gamma': 'scale', 'model__kernel': 'rbf'},
  {'model__C': 100, 'model__gamma': 'auto', 'model__kernel': 'rbf'},
  {'model__C': 100, 'model__gamma': 0.01, 'model__kernel': 'rbf'},
  {'model__C': 100, 'model__gamma': 0.1, 'model__kernel': 'rbf'},
  {'model__C': 0.1,
   'model__degree': 2,
   'model__gamma': 'scale',
   'model__kernel': 'poly'},
  {'model__C': 0.1,
   'model__degree': 2,
   'model__gamma': 'auto',
   'model__kernel': 'poly'},
  {'model__C': 0.1,
   'model__degree': 2,
   'model__gamma': 0.01,
   'model__kernel': 'poly'},
  {'model__C': 0.1,
   'model__degree': 2,
   'model__gamma': 0.1,
   'model__kernel': 'poly'},
  {'model__C': 0.1,
   'model__degree': 3,
   'model__gamma': 'scale',
   'model__kernel': 'poly'},
  {'model__C': 0.1,
   'model__degree': 3,
   'model__gamma': 'auto',
   'model__kernel': 'poly'},
  {'model__C': 0.1,
   'model__degree': 3,
   'model__gamma': 0.01,
   'model__kernel': 'poly'},
  {'model__C': 0.1,
   'model__degree': 3,
   'model__gamma': 0.1,
   'model__kernel': 'poly'},
  {'model__C': 0.1,
   'model__degree': 4,
   'model__gamma': 'scale',
   'model__kernel': 'poly'},
  {'model__C': 0.1,
   'model__degree': 4,
   'model__gamma': 'auto',
   'model__kernel': 'poly'},
  {'model__C': 0.1,
   'model__degree': 4,
   'model__gamma': 0.01,
   'model__kernel': 'poly'},
  {'model__C': 0.1,
   'model__degree': 4,
   'model__gamma': 0.1,
   'model__kernel': 'poly'},
  {'model__C': 1,
   'model__degree': 2,
   'model__gamma': 'scale',
   'model__kernel': 'poly'},
  {'model__C': 1,
   'model__degree': 2,
   'model__gamma': 'auto',
   'model__kernel': 'poly'},
  {'model__C': 1,
   'model__degree': 2,
   'model__gamma': 0.01,
   'model__kernel': 'poly'},
  {'model__C': 1,
   'model__degree': 2,
   'model__gamma': 0.1,
   'model__kernel': 'poly'},
  {'model__C': 1,
   'model__degree': 3,
   'model__gamma': 'scale',
   'model__kernel': 'poly'},
  {'model__C': 1,
   'model__degree': 3,
   'model__gamma': 'auto',
   'model__kernel': 'poly'},
  {'model__C': 1,
   'model__degree': 3,
   'model__gamma': 0.01,
   'model__kernel': 'poly'},
  {'model__C': 1,
   'model__degree': 3,
   'model__gamma': 0.1,
   'model__kernel': 'poly'},
  {'model__C': 1,
   'model__degree': 4,
   'model__gamma': 'scale',
   'model__kernel': 'poly'},
  {'model__C': 1,
   'model__degree': 4,
   'model__gamma': 'auto',
   'model__kernel': 'poly'},
  {'model__C': 1,
   'model__degree': 4,
   'model__gamma': 0.01,
   'model__kernel': 'poly'},
  {'model__C': 1,
   'model__degree': 4,
   'model__gamma': 0.1,
   'model__kernel': 'poly'},
  {'model__C': 10,
   'model__degree': 2,
   'model__gamma': 'scale',
   'model__kernel': 'poly'},
  {'model__C': 10,
   'model__degree': 2,
   'model__gamma': 'auto',
   'model__kernel': 'poly'},
  {'model__C': 10,
   'model__degree': 2,
   'model__gamma': 0.01,
   'model__kernel': 'poly'},
  {'model__C': 10,
   'model__degree': 2,
   'model__gamma': 0.1,
   'model__kernel': 'poly'},
  {'model__C': 10,
   'model__degree': 3,
   'model__gamma': 'scale',
   'model__kernel': 'poly'},
  {'model__C': 10,
   'model__degree': 3,
   'model__gamma': 'auto',
   'model__kernel': 'poly'},
  {'model__C': 10,
   'model__degree': 3,
   'model__gamma': 0.01,
   'model__kernel': 'poly'},
  {'model__C': 10,
   'model__degree': 3,
   'model__gamma': 0.1,
   'model__kernel': 'poly'},
  {'model__C': 10,
   'model__degree': 4,
   'model__gamma': 'scale',
   'model__kernel': 'poly'},
  {'model__C': 10,
   'model__degree': 4,
   'model__gamma': 'auto',
   'model__kernel': 'poly'},
  {'model__C': 10,
   'model__degree': 4,
   'model__gamma': 0.01,
   'model__kernel': 'poly'},
  {'model__C': 10,
   'model__degree': 4,
   'model__gamma': 0.1,
   'model__kernel': 'poly'}],
 'split0_test_score': array([0.77235772, 0.75609756, 0.75609756, 0.75609756, 0.77235772,
        0.77235772, 0.6504065 , 0.76422764, 0.73170732, 0.73170732,
        0.75609756, 0.7398374 , 0.72357724, 0.72357724, 0.76422764,
        0.69918699, 0.70731707, 0.70731707, 0.71544715, 0.70731707,
        0.65853659, 0.65853659, 0.6504065 , 0.63414634, 0.70731707,
        0.70731707, 0.6504065 , 0.67479675, 0.70731707, 0.70731707,
        0.6504065 , 0.6504065 , 0.71544715, 0.71544715, 0.6504065 ,
        0.72357724, 0.70731707, 0.70731707, 0.6504065 , 0.71544715,
        0.69918699, 0.69918699, 0.6504065 , 0.68292683, 0.69105691,
        0.69105691, 0.63414634, 0.69105691, 0.7398374 , 0.7398374 ,
        0.63414634, 0.73170732, 0.69105691, 0.69105691, 0.64227642,
        0.68292683]),
 'split1_test_score': array([0.7804878 , 0.78861789, 0.78861789, 0.78861789, 0.77235772,
        0.77235772, 0.6504065 , 0.77235772, 0.7398374 , 0.7398374 ,
        0.7804878 , 0.75609756, 0.70731707, 0.70731707, 0.79674797,
        0.77235772, 0.66666667, 0.66666667, 0.7398374 , 0.67479675,
        0.67479675, 0.67479675, 0.6504065 , 0.65853659, 0.69918699,
        0.69918699, 0.6504065 , 0.67479675, 0.65853659, 0.65853659,
        0.6504065 , 0.66666667, 0.72357724, 0.72357724, 0.6504065 ,
        0.69918699, 0.74796748, 0.74796748, 0.6504065 , 0.7398374 ,
        0.71544715, 0.71544715, 0.6504065 , 0.69918699, 0.74796748,
        0.74796748, 0.65853659, 0.73170732, 0.74796748, 0.74796748,
        0.6504065 , 0.70731707, 0.67479675, 0.67479675, 0.6504065 ,
        0.7398374 ]),
 'split2_test_score': array([0.75609756, 0.75609756, 0.75609756, 0.75609756, 0.7398374 ,
        0.7398374 , 0.6504065 , 0.73170732, 0.76422764, 0.76422764,
        0.75609756, 0.7804878 , 0.68292683, 0.68292683, 0.74796748,
        0.69105691, 0.65853659, 0.65853659, 0.76422764, 0.66666667,
        0.65853659, 0.65853659, 0.6504065 , 0.6504065 , 0.68292683,
        0.68292683, 0.6504065 , 0.67479675, 0.69105691, 0.69105691,
        0.6504065 , 0.67479675, 0.67479675, 0.67479675, 0.6504065 ,
        0.68292683, 0.71544715, 0.71544715, 0.6504065 , 0.69105691,
        0.71544715, 0.71544715, 0.6504065 , 0.70731707, 0.70731707,
        0.70731707, 0.6504065 , 0.67479675, 0.73170732, 0.73170732,
        0.6504065 , 0.73170732, 0.69918699, 0.69918699, 0.6504065 ,
        0.69105691]),
 'split3_test_score': array([0.78861789, 0.77235772, 0.77235772, 0.76422764, 0.72357724,
        0.72357724, 0.6504065 , 0.7398374 , 0.77235772, 0.77235772,
        0.7804878 , 0.75609756, 0.73170732, 0.73170732, 0.7804878 ,
        0.7398374 , 0.66666667, 0.66666667, 0.77235772, 0.65853659,
        0.67479675, 0.67479675, 0.6504065 , 0.65853659, 0.71544715,
        0.71544715, 0.6504065 , 0.69105691, 0.69105691, 0.69105691,
        0.6504065 , 0.69105691, 0.66666667, 0.66666667, 0.6504065 ,
        0.67479675, 0.71544715, 0.71544715, 0.6504065 , 0.73170732,
        0.69105691, 0.69105691, 0.6504065 , 0.70731707, 0.69918699,
        0.69918699, 0.65853659, 0.69105691, 0.69918699, 0.69918699,
        0.6504065 , 0.70731707, 0.67479675, 0.67479675, 0.6504065 ,
        0.68292683]),
 'split4_test_score': array([0.79508197, 0.80327869, 0.80327869, 0.80327869, 0.76229508,
        0.76229508, 0.6557377 , 0.76229508, 0.75409836, 0.75409836,
        0.81147541, 0.76229508, 0.77868852, 0.77868852, 0.80327869,
        0.77868852, 0.75409836, 0.75409836, 0.81967213, 0.71311475,
        0.68032787, 0.68032787, 0.6557377 , 0.66393443, 0.76229508,
        0.76229508, 0.6557377 , 0.71311475, 0.72131148, 0.72131148,
        0.6557377 , 0.68032787, 0.71311475, 0.71311475, 0.6557377 ,
        0.73770492, 0.77868852, 0.77868852, 0.6557377 , 0.78688525,
        0.74590164, 0.74590164, 0.6557377 , 0.76229508, 0.7295082 ,
        0.7295082 , 0.66393443, 0.7295082 , 0.79508197, 0.79508197,
        0.6557377 , 0.77868852, 0.69672131, 0.69672131, 0.6557377 ,
        0.7295082 ]),
 'mean_test_score': array([0.77852859, 0.77528988, 0.77528988, 0.77366387, 0.75408503,
        0.75408503, 0.65147274, 0.75408503, 0.75244569, 0.75244569,
        0.77692923, 0.75896308, 0.7248434 , 0.7248434 , 0.77854192,
        0.73622551, 0.69065707, 0.69065707, 0.76230841, 0.68408637,
        0.66939891, 0.66939891, 0.65147274, 0.65311209, 0.71343463,
        0.71343463, 0.65147274, 0.68571238, 0.69385579, 0.69385579,
        0.65147274, 0.67265094, 0.69872051, 0.69872051, 0.65147274,
        0.70363854, 0.73297348, 0.73297348, 0.65147274, 0.73298681,
        0.71340797, 0.71340797, 0.65147274, 0.71180861, 0.71500733,
        0.71500733, 0.65311209, 0.70362522, 0.74275623, 0.74275623,
        0.64822071, 0.73134746, 0.68731174, 0.68731174, 0.64984673,
        0.70525123]),
 'std_test_score': array([0.01357113, 0.01847321, 0.01847321, 0.01900975, 0.01933343,
        0.01933343, 0.00213248, 0.01554301, 0.01501389, 0.01501389,
        0.02042881, 0.01308916, 0.03166129, 0.03166129, 0.02042963,
        0.03614898, 0.03601432, 0.03601432, 0.0349176 , 0.02202202,
        0.00909611, 0.00909611, 0.00213248, 0.01042107, 0.02669284,
        0.02669284, 0.00213248, 0.01507917, 0.02096728, 0.02096728,
        0.00213248, 0.01365977, 0.0232578 , 0.0232578 , 0.00213248,
        0.02382734, 0.02678537, 0.02678537, 0.00213248, 0.03168396,
        0.01879341, 0.01879341, 0.00213248, 0.02676824, 0.02087914,
        0.02087914, 0.01042107, 0.02282778, 0.03096455, 0.03096455,
        0.00733384, 0.02606283, 0.01055308, 0.01055308, 0.00431169,
        0.02442474]),
 'rank_test_score': array([ 2,  4,  4,  6,  9,  9, 48,  9, 12, 12,  3,  8, 21, 21,  1, 16, 37,
        37,  7, 42, 44, 44, 48, 46, 25, 25, 48, 41, 35, 35, 48, 43, 33, 33,
        48, 31, 18, 18, 48, 17, 27, 27, 48, 29, 23, 23, 46, 32, 14, 14, 56,
        20, 39, 39, 55, 30], dtype=int32),
 'split0_train_score': array([0.79633401, 0.80651731, 0.80651731, 0.80651731, 0.79429735,
        0.79429735, 0.65173116, 0.79022403, 0.85336049, 0.85336049,
        0.80244399, 0.84317719, 0.91242363, 0.91242363, 0.80855397,
        0.89613035, 0.97759674, 0.97759674, 0.84114053, 0.96334012,
        0.700611  , 0.700611  , 0.65173116, 0.67820774, 0.75152749,
        0.75152749, 0.65173116, 0.7311609 , 0.74338086, 0.74338086,
        0.65173116, 0.71283096, 0.75152749, 0.75152749, 0.65173116,
        0.7413442 , 0.81059063, 0.81059063, 0.65173116, 0.79633401,
        0.81873727, 0.81873727, 0.65173116, 0.77800407, 0.76985743,
        0.76985743, 0.67820774, 0.76782077, 0.86354379, 0.86354379,
        0.6598778 , 0.85947047, 0.89205703, 0.89205703, 0.65173116,
        0.86354379]),
 'split1_train_score': array([0.78818737, 0.79226069, 0.79226069, 0.79633401, 0.76985743,
        0.76985743, 0.65173116, 0.77393075, 0.83299389, 0.83299389,
        0.78411405, 0.82484725, 0.89205703, 0.89205703, 0.80040733,
        0.87372709, 0.97148676, 0.97148676, 0.81670061, 0.94501018,
        0.67209776, 0.67209776, 0.65173116, 0.6598778 , 0.74338086,
        0.74338086, 0.65173116, 0.71690428, 0.72505092, 0.72505092,
        0.65173116, 0.7107943 , 0.73727088, 0.73727088, 0.65173116,
        0.72708758, 0.80651731, 0.80651731, 0.65173116, 0.79226069,
        0.79837067, 0.79837067, 0.65173116, 0.77393075, 0.74949084,
        0.74949084, 0.6598778 , 0.76171079, 0.86150713, 0.86150713,
        0.65173116, 0.84521385, 0.87576375, 0.87576375, 0.65173116,
        0.84521385]),
 'split2_train_score': array([0.80040733, 0.79837067, 0.79837067, 0.79837067, 0.77596741,
        0.77596741, 0.65173116, 0.78207739, 0.84928717, 0.84928717,
        0.79226069, 0.84114053, 0.91649695, 0.91649695, 0.80855397,
        0.89205703, 0.97148676, 0.97148676, 0.82892057, 0.9592668 ,
        0.6700611 , 0.6700611 , 0.65173116, 0.66395112, 0.73727088,
        0.73727088, 0.65173116, 0.71690428, 0.73319756, 0.73319756,

In [23]:
grid_results_df = pd.DataFrame(grid.cv_results_)

grid_results_df = grid_results_df[["params", "mean_train_score", "mean_test_score","rank_test_score"]].sort_values("rank_test_score")

grid_results_df

                                               params  ...  rank_test_score
14  {'model__C': 10, 'model__gamma': 0.01, 'model_...  ...                1
0        {'model__C': 0.1, 'model__kernel': 'linear'}  ...                2
10  {'model__C': 1, 'model__gamma': 0.01, 'model__...  ...                3
1          {'model__C': 1, 'model__kernel': 'linear'}  ...                4
2         {'model__C': 10, 'model__kernel': 'linear'}  ...                4
3        {'model__C': 100, 'model__kernel': 'linear'}  ...                6
18  {'model__C': 100, 'model__gamma': 0.01, 'model...  ...                7
11  {'model__C': 1, 'model__gamma': 0.1, 'model__k...  ...                8
5   {'model__C': 0.1, 'model__gamma': 'auto', 'mod...  ...                9
7   {'model__C': 0.1, 'model__gamma': 0.1, 'model_...  ...                9
4   {'model__C': 0.1, 'model__gamma': 'scale', 'mo...  ...                9
8   {'model__C': 1, 'model__gamma': 'scale', 'mode...  ...               12
9   {'model__C': 1, 'model__gamma': 'auto', 'model...  ...               12
49  {'model__C': 10, 'model__degree': 3, 'model__g...  ...               14
48  {'model__C': 10, 'model__degree': 3, 'model__g...  ...               14
15  {'model__C': 10, 'model__gamma': 0.1, 'model__...  ...               16
39  {'model__C': 1, 'model__degree': 3, 'model__ga...  ...               17
36  {'model__C': 1, 'model__degree': 3, 'model__ga...  ...               18
37  {'model__C': 1, 'model__degree': 3, 'model__ga...  ...               18
51  {'model__C': 10, 'model__degree': 3, 'model__g...  ...               20
12  {'model__C': 10, 'model__gamma': 'scale', 'mod...  ...               21
13  {'model__C': 10, 'model__gamma': 'auto', 'mode...  ...               21
45  {'model__C': 10, 'model__degree': 2, 'model__g...  ...               23
44  {'model__C': 10, 'model__degree': 2, 'model__g...  ...               23
25  {'model__C': 0.1, 'model__degree': 3, 'model__...  ...               25
24  {'model__C': 0.1, 'model__degree': 3, 'model__...  ...               25
40  {'model__C': 1, 'model__degree': 4, 'model__ga...  ...               27
41  {'model__C': 1, 'model__degree': 4, 'model__ga...  ...               27
43  {'model__C': 1, 'model__degree': 4, 'model__ga...  ...               29
55  {'model__C': 10, 'model__degree': 4, 'model__g...  ...               30
35  {'model__C': 1, 'model__degree': 2, 'model__ga...  ...               31
47  {'model__C': 10, 'model__degree': 2, 'model__g...  ...               32
33  {'model__C': 1, 'model__degree': 2, 'model__ga...  ...               33
32  {'model__C': 1, 'model__degree': 2, 'model__ga...  ...               33
29  {'model__C': 0.1, 'model__degree': 4, 'model__...  ...               35
28  {'model__C': 0.1, 'model__degree': 4, 'model__...  ...               35
16  {'model__C': 100, 'model__gamma': 'scale', 'mo...  ...               37
17  {'model__C': 100, 'model__gamma': 'auto', 'mod...  ...               37
53  {'model__C': 10, 'model__degree': 4, 'model__g...  ...               39
52  {'model__C': 10, 'model__degree': 4, 'model__g...  ...               39
27  {'model__C': 0.1, 'model__degree': 3, 'model__...  ...               41
19  {'model__C': 100, 'model__gamma': 0.1, 'model_...  ...               42
31  {'model__C': 0.1, 'model__degree': 4, 'model__...  ...               43
21  {'model__C': 0.1, 'model__degree': 2, 'model__...  ...               44
20  {'model__C': 0.1, 'model__degree': 2, 'model__...  ...               44
23  {'model__C': 0.1, 'model__degree': 2, 'model__...  ...               46
46  {'model__C': 10, 'model__degree': 2, 'model__g...  ...               46
6   {'model__C': 0.1, 'model__gamma': 0.01, 'model...  ...               48
30  {'model__C': 0.1, 'model__degree': 4, 'model__...  ...               48
26  {'model__C': 0.1, 'model__degree': 3, 'model__...  ...               48
22  {'model__C': 0.1, 'model__degree': 2, 'model__...  ...               48
34  {'model__C': 1, 'model__degree': 2, 'model__ga...  ...               48
42  {'model__C': 1, 'model__degree': 4, 'model__ga...  ...               48
38  {'model__C': 1, 'model__degree': 3, 'model__ga...  ...               48
54  {'model__C': 10, 'model__degree': 4, 'model__g...  ...               55
50  {'model__C': 10, 'model__degree': 3, 'model__g...  ...               56

[56 rows x 4 columns]

In [24]:
len(grid_results_df)

56

**4. Randomized Search CV(Tries Random Combinations)**

In [25]:
param_dist = [
    #Linear
    {
        "model__kernel" : ["linear"],
        "model__C" : loguniform(0.01, 100)
    },
    #RBF
    {
        "model__kernel" : ["rbf"],
        "model__C" : loguniform(0.01, 1000),
        "model__gamma" : loguniform(0.001, 10)
    },
    #Poly
    {
        "model__kernel" : ["poly"],
        "model__C" : loguniform(0.01, 100),
        "model__gamma" : loguniform(0.001, 1)
    }
]

In [26]:
random_search = RandomizedSearchCV(
    estimator=pipeline,
    param_distributions=param_dist,
    n_iter=20,
    cv=5,
    scoring="accuracy",
    random_state=42,
    return_train_score=True,
    n_jobs=-1
)

In [27]:
random_search.fit(X_train,y_train)

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('scalar', StandardScaler()),
                                             ('model', SVC())]),
                   n_iter=20, n_jobs=-1,
                   param_distributions=[{'model__C': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000001FF93B15FD0>,
                                         'model__kernel': ['linear']},
                                        {'model__C': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000001FFD3B4C...
                                         'model__gamma': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000001FFD3B4E210>,
                                         'model__kernel': ['rbf']},
                                        {'model__C': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000001FFD3CAD6E0>,
                                         'model__gamma': <scipy.stats._distn_infrastructure.rv_continuous_frozen object at 0x000001FFD3CAD350>,
                                         'model__kernel': ['poly']}],
                   random_state=42, return_train_score=True,
                   scoring='accuracy')

In [28]:
print("RANDOMIZED SEARCH CV - Results:")
print("Best params:", random_search.best_params_)
print("Best CV Accuracy:",random_search.best_score_)

RANDOMIZED SEARCH CV - Results:
Best params: {'model__C': np.float64(1.335916680165182), 'model__gamma': np.float64(0.00678838791242122), 'model__kernel': 'rbf'}
Best CV Accuracy: 0.7769292283086766

In [31]:
test_accuracy = round(random_search.score(X_test, y_test)*100,2)
print(f"Test Accuracy: {test_accuracy}%")

Test Accuracy: 73.38%

In [32]:
random_results_df = pd.DataFrame(random_search.cv_results_)

random_results_df = random_results_df[["params", "mean_train_score", "mean_test_score","rank_test_score"]].sort_values("rank_test_score")

random_results_df

                                               params  ...  rank_test_score
19  {'model__C': 1.335916680165182, 'model__gamma'...  ...                1
3   {'model__C': 2.5378155082656657, 'model__kerne...  ...                2
8   {'model__C': 1.256315277393867, 'model__kernel...  ...                2
12  {'model__C': 0.015339162591163621, 'model__ker...  ...                4
6   {'model__C': 2.950706670790534, 'model__kernel...  ...                5
1   {'model__C': 2.440060709081755, 'model__kernel...  ...                5
7   {'model__C': 4.205156450913866, 'model__gamma'...  ...                7
16  {'model__C': 26.373339933815235, 'model__gamma...  ...                8
4   {'model__C': 0.012087541473056965, 'model__gam...  ...                9
10  {'model__C': 0.6672367170464207, 'model__gamma...  ...               10
17  {'model__C': 2.754143921332031, 'model__gamma'...  ...               11
11  {'model__C': 0.338725556585215, 'model__gamma'...  ...               12
13  {'model__C': 5.2629610310767445, 'model__gamma...  ...               13
5   {'model__C': 0.1152644954031561, 'model__gamma...  ...               14
0   {'model__C': 15.352246941973492, 'model__gamma...  ...               14
2   {'model__C': 0.060252157362038566, 'model__gam...  ...               14
15  {'model__C': 0.8454394570684998, 'model__gamma...  ...               14
14  {'model__C': 555.1721685244722, 'model__gamma'...  ...               14
9   {'model__C': 0.03613894271216528, 'model__gamm...  ...               14
18  {'model__C': 43.37920697490943, 'model__gamma'...  ...               20

[20 rows x 4 columns]