**Standardization and Normalization**

Dataset: Pima Indians Diabetes: Diabetes.csv
**Goal:**
- Apply StandardScaler and MinMaxScaler(Only one needed in the actual Workflow)
- Fit Scalers on TRAIN Only
- Transform both TRAIN and TEST

In [4]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler

pd.set_option("display.max_columns",None)
pd.set_option("display.float_format",lambda x: '%.3f' %x)

**1. Load Dataset**

In [5]:
df = pd.read_csv("diabetes.csv")
print("Shape:",df.shape)
df.head()

Shape: (768, 9)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.600,0.627,50,1
1,1,85,66,29,0,26.600,0.351,31,0
2,8,183,64,0,0,23.300,0.672,32,1
3,1,89,66,23,94,28.100,0.167,21,0
4,0,137,40,35,168,43.100,2.288,33,1

**2. Train test Split**

In [6]:
X = df.drop(columns=["Outcome"])
y = df["Outcome"]

X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 42,
    stratify = y
)

print("\n Shapes after Split:")
print("X_train Shape:",X_train.shape)
print("X_test Shape:",X_test.shape)

num_cols = X_train.select_dtypes(include=[np.number]).columns.tolist()
cat_cols = [col for col in X_train.columns if col not in num_cols]

 Shapes after Split:
X_train Shape: (614, 8)
X_test Shape: (154, 8)

In [8]:
print("Numerical Columns:",num_cols)
print("Categorical Columns:",cat_cols)

Numerical Columns: ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']
Categorical Columns: []

**3. Standardization - StandardScaler**
- Mean ~ 0
- Standard Deviation ~ 1
- **z = (x - mean)/standard Deviation**

In [7]:
scaler = StandardScaler()

In [9]:
scaler.fit(X_train[num_cols])

StandardScaler()

In [11]:
X_train_std = X_train.copy()
X_test_std = X_test.copy()

In [12]:
X_train_std[num_cols] = scaler.transform(X_train[num_cols])
X_test_std[num_cols] = scaler.transform(X_test[num_cols])

In [14]:
print(X_train_std.describe().T)

                           count   mean   std    min    25%    50%   75%   max
Pregnancies              614.000 -0.000 1.001 -1.153 -0.851 -0.247 0.659 3.980
Glucose                  614.000  0.000 1.001 -3.834 -0.695 -0.124 0.605 2.476
BloodPressure            614.000 -0.000 1.001 -3.777 -0.378  0.139 0.574 2.858
SkinThickness            614.000 -0.000 1.001 -1.311 -1.311  0.140 0.708 4.937
Insulin                  614.000 -0.000 1.001 -0.731 -0.731 -0.355 0.477 6.181
BMI                      614.000  0.000 1.001 -4.070 -0.569  0.042 0.576 4.472
DiabetesPedigreeFunction 614.000 -0.000 1.001 -1.192 -0.704 -0.288 0.490 5.610
Age                      614.000 -0.000 1.001 -1.046 -0.792 -0.369 0.646 4.029

**4. Normalization - MinMaxScaler**
- Min-Value = 0
- Max_Value = 1
- **X_scaled = (X - xXmin) / (X_max - X_min)**

In [16]:
mm_scaler = MinMaxScaler()

mm_scaler.fit(X_train[num_cols])

X_train_mm = X_train.copy()
X_test_mm = X_test.copy()

X_train_mm[num_cols] = mm_scaler.transform(X_train[num_cols])
X_test_mm[num_cols] = mm_scaler.transform(X_test[num_cols])

print(X_train_mm.describe().T)

                           count  mean   std   min   25%   50%   75%   max
Pregnancies              614.000 0.225 0.195 0.000 0.059 0.176 0.353 1.000
Glucose                  614.000 0.608 0.159 0.000 0.497 0.588 0.704 1.000
BloodPressure            614.000 0.569 0.151 0.000 0.512 0.590 0.656 1.000
SkinThickness            614.000 0.210 0.160 0.000 0.000 0.232 0.323 1.000
Insulin                  614.000 0.106 0.145 0.000 0.000 0.054 0.175 1.000
BMI                      614.000 0.477 0.117 0.000 0.410 0.481 0.544 1.000
DiabetesPedigreeFunction 614.000 0.175 0.147 0.000 0.072 0.133 0.247 1.000
Age                      614.000 0.206 0.197 0.000 0.050 0.133 0.333 1.000

In [17]:
X_train_mm.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
353,0.059,0.452,0.508,0.121,0.058,0.405,0.221,0.050
711,0.294,0.633,0.639,0.273,0.030,0.441,0.158,0.317
373,0.118,0.528,0.475,0.404,0.126,0.520,0.063,0.067
46,0.059,0.734,0.459,0.000,0.000,0.443,0.214,0.133
682,0.000,0.477,0.525,0.394,0.141,0.665,0.126,0.017

**5. Saving the Scaled Versions**

In [18]:
train_std = X_train_std.copy()
train_std["Outcome"] = y_train.values

test_std = X_test_std.copy()
test_std["Outcome"] = y_test.values

train_mm = X_train_mm.copy()
train_mm["Outcome"] = y_train.values

test_mm = X_test_mm.copy()
test_mm["Outcome"] = y_test.values

train_std.to_csv("diabetes_trained_standard_scaled.csv",index = False)
train_std.to_csv("diabetes_test_standard_scaled.csv",index = False)

train_std.to_csv("diabetes_train_minmax_scaled.csv",index = False)
train_std.to_csv("diabetes_test_minmax_scaled.csv",index = False)

print("\n - Saved Files")
print("- diabetes_trained_standard_scaler.csv")
print("- diabetes_test_standard_scaled.csv")
print("- diabetes_train_minmax_scaled.csv")
print("- diabetes_test_minmax_scaled.csv")

 - Saved Files
- diabetes_trained_standard_scaler.csv
- diabetes_test_standard_scaled.csv
- diabetes_train_minmax_scaled.csv
- diabetes_test_minmax_scaled.csv